### PR TITLE
Feature/remove bid locations

### PR DESCRIPTION
**Pull request by rtirserio**
Resolves TM-343.

An API change is required to enable the removal of a bid in anything other than the draft status. 

This will show the Remove Bid link in place of the actions drop down on the bid tracker when the bid is in draft, submitted or handshake offered statuses.

I also refactored the Are you Sure link into its own component since that is used on the clear filter control.

### CODE REVIEW

**Comment by rtirserio** [comment]
The API has been updated to support removing bids from draft, submitted and handshake offered bids.

**Comment by mjoyce91** [comment]
Does it seem odd that you can delete a bid in "handshake offered" status? Shouldn't you have to decline it? Otherwise, you have the ability to either "delete" it or "decline" it, which doesn't really make sense.

**Comment by rtirserio** [comment]
I would think that if you decline the handshake it would remain in your list. This would allow for the user to just remove in one step. On the API side, the handshake could be declined and the bid removed

**Comment by mjoyce91** [comment]
That's true, as long as the API also "declined" it - otherwise the position "owner" would never hear back that it was declined.

**Comment by rtirserio** [comment]
@mjoyce91 updated this to use the can_delete property

**Pull request merged**
