### PR TITLE
Updating HS Notifications

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
Updating the HS notifications to have a more accurate Revoked one.

1st commit: removed all the Candidate Manager stuff and extra css for the Share Bureau AB Modal tooltip.
2nd commit: code to display only a single handshake_bidder notification per cp_id
other commits: revoke HS notification

Dual Merge: [BE PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/561)

### CODE REVIEW

**Review by mjoyce91 — APPROVED** [review]

**Comment by mjoyce91** [comment]
This is showing the Revoke toast for the bidder even after the HS is offered to them. Any cleanup I need to do to my DB?

**Comment by mjoyce91** [comment]
Screen Shot 2021-07-01 at 1 18 12 PM

Maybe it's just the wording? The title and the message in the toast don't match

**Comment by elizabeth-jimenez** [comment]
> This is showing the Revoke toast for the bidder even after the HS is offered to them. Any cleanup I need to do to my DB?

I doubt it, I thought it was working 😭  I'll look into it

**Comment by elizabeth-jimenez** [comment]
image
this is what Bid Tracker button looks like in the middle instead.

**Review by mjoyce91 — APPROVED** [review]

**Pull request merged**
