### PR TITLE
Bid Tracker Text - Accepted -> Registered

### PR DESCRIPTION
**Pull request by mjoyce91**

### CODE REVIEW

**Comment by scott062** [comment]
@mjoyce91 Sorry I'm confused by this status and the steps.  I thought it is `Accepted` then `Registered` - where a HS is offered by the bureau, accepted by the Client, and then finally registered by the CDO. So the HS accepted is the important step for the clients but the registering of the HS is only pertinent to the CDO's hence it is abstracted from bidders.

**Comment by scott062** [comment]
image

**Comment by mjoyce91** [comment]
No, those are good points @scott062. I'll update

**Comment by mjoyce91** [comment]
@scott062 - made updates

**Pull request merged**
