### PR TITLE
make Location consistent for PV favorite

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
Confirmed the following are coming through in v2/futureVacancies (all the data points needed for getPostName())
- location_country
- pos_location_code
- location_city
- location_state

**Comment by SidelineCory24** [comment]
Tested that this works, will hold off on approval based off of Product Owners feedback.

**Comment by scott062** [comment]
image
Can we strip the white space easily or not really?

**Review by scott062 — APPROVED** [review]
🇺🇸

**Review by SidelineCory24 — APPROVED** [review]
Looks good to go! 🚀

**Pull request merged**
