### PR TITLE
TM-2999 - Position Search Sticky Filters

### PR DESCRIPTION
**Pull request by pveland621**
Ticket Link: https://metaphase.atlassian.net/browse/TM-2999

Some notes on the ACs from the ticket:

`1. Search and filters remain on screen when scrolling down the Position Search page` - Discussed with Kate, LOE grows pretty fast when stacking sticky components so we decided to not make the search bar sticky since the main ask of this ticket is really to have the filters scroll down with the user.

`2. Your selections and Sort by, view by, etc do NOT remain on screen (dependent on LOE)` - Discussed with Kate, having these be sticky was not difficult so we included it

---

ACs:

1. Verify filters and controls ('Your Selections', 'Sort By', etc.) become sticky components when you scroll down the Position Results page
2. Verify filters and controls become sticky and are placed correctly when a CDO is using the 'Search As Client' view (which adds the client view header)
3. Verify filters and controls become sticky and are placed correctly when a user selects a Tandem Search
4. TalentMAP Alerts and banners do NOT remain on screen
5. Verify text of “Exit Client View' size matches ‘Client Dashboard’ on the CDO Client Proxy View

### CODE REVIEW

**Comment by pveland621** [comment]
image

Probably need input here on if this is alright, when the search results become sticky, it has this little like drop shadow to the left - probably alright to keep in or should I look for a solution?

**Comment by pveland621** [comment]
image

image

Also another note - the first picture is just the normal unexpanded filters, and the second picture is when you expand a filter which has many options. Expanding one of those filters pushes off the bottom filters from being able to be seen. I implemented having two scroll bars on the component but after discussion with Kate, we agreed that having two scroll bars on one component is too messy and the user should be able to figure out that they need to close the previous filter to see all of the filters again

**Comment by elizabeth-jimenez** [comment]
> image
> 
> image
> 
> Also another note - the first picture is just the normal unexpanded filters, and the second picture is when you expand a filter which has many options. Expanding one of those filters pushes off the bottom filters from being able to be seen. I implemented having two scroll bars on the component but after discussion with Kate, we agreed that having two scroll bars on one component is too messy and the user should be able to figure out that they need to close the previous filter to see all of the filters again

Can you keep the Scroll functionality w.o. showing the scroll bar?

**Comment by pveland621** [comment]
> > image
> > image
> > Also another note - the first picture is just the normal unexpanded filters, and the second picture is when you expand a filter which has many options. Expanding one of those filters pushes off the bottom filters from being able to be seen. I implemented having two scroll bars on the component but after discussion with Kate, we agreed that having two scroll bars on one component is too messy and the user should be able to figure out that they need to close the previous filter to see all of the filters again
> 
> Can you keep the Scroll functionality w.o. showing the scroll bar?

Been messing around with overflow: hidden but now I'm getting into weird behavior where the second scroll bar only appears on some expanded filters but not all. Will continue looking into it

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
> image

For the above SS and this one, you may want to add a background color to the filters, as they won't always be able to rely on background color of the main page anymore

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
image
We'll want to add a background color to this as well.

**Comment by elizabeth-jimenez** [comment]
> > Can you keep the Scroll functionality w.o. showing the scroll bar?
> 
> Been messing around with overflow: hidden but now I'm getting into weird behavior where the second scroll bar only appears on some expanded filters but not all. Will continue looking into it

i'm not seeing the same behavior 🤔

**Comment by elizabeth-jimenez** [comment]
http://jsfiddle.net/5GCsJ/954/ check this one out

**Comment by pveland621** [comment]
More weird behavior - to replicate, scroll down to activate sticky filters, expand languages -> languages plus sign then scroll down the filters container. A bunch of white space is added at the bottom. Will look into tomorrow


image

**Comment by pveland621** [comment]
Also seeing this with tutorial steps. I'm not sure how to fix this, as the tutorial snaps to the tandem toggle but in doing so scrolls down the page making the filters sticky and the tutorial highlights the old position of the tandem toggle

image

**Comment by andrews-john** [comment]
This all looks good to me. My only suggestion would be to maybe add a bit of padding/margin to the open positions column when it becomes sticky, but I can also see how that maybe lets the clear filters text bleed over, and maybe we don't want that part to be sticky. Either way, for me all the action items are working!

**Comment by andrews-john** [comment]
For Elizabeth's feedback:

- Not seeing bg color on the filter area
image

**Review by andrews-john — APPROVED** [review]
Looks good to me. Ill defer to Elizabeth if she wants to review it as well, but for me its good to go

**Pull request merged**
