### PR TITLE
TM-4844-CDO-UI

### PR DESCRIPTION
**Pull request by cagbakwu**
Dual Merge: 
- [API PR](linkToAPIPR)
[Ticket](https://metaphase.atlassian.net/browse/TM-4844)

FE is ready but won't update anything until BE is complete.

### CODE REVIEW

**Comment by M00staff** [comment]
not sure why you mentioned this was ready to review in the devs chat - its still marked as a WiP and is pretty clearly dependent on a backend part. 

the whole point of posting PR's there is to take the guess work and onus off of the one reviewing

**Comment by cagbakwu** [comment]
> not sure why you mentioned this was ready to review in the devs chat - its still marked as a WiP and is pretty clearly dependent on a backend part.
> 
> the whole point of posting PR's there is to take the guess work and onus off of the one reviewing

@M00staff this can be approved and not affect the backend. Only changes that were need here were the endpoint and data changes. It wouldn't affect anything to have this merged.

**Comment by M00staff** [comment]
> > not sure why you mentioned this was ready to review in the devs chat - its still marked as a WiP and is pretty clearly dependent on a backend part.
> > the whole point of posting PR's there is to take the guess work and onus off of the one reviewing
> 
> @M00staff this can be approved and not affect the backend. Only changes that were need here were the endpoint and data changes. It wouldn't affect anything to have this merged.

What's the reasoning to merge this in now?

**Comment by cagbakwu** [comment]
> > > not sure why you mentioned this was ready to review in the devs chat - its still marked as a WiP and is pretty clearly dependent on a backend part.
> > > the whole point of posting PR's there is to take the guess work and onus off of the one reviewing
> > 
> > 
> > @M00staff this can be approved and not affect the backend. Only changes that were need here were the endpoint and data changes. It wouldn't affect anything to have this merged.
> 
> What's the reasoning to merge this in now?

None really, I'll hold it out until the BE is integrated.

**Pull request closed without merging**
