### PR TITLE
Update dashboard styles and content based on QA

### PR DESCRIPTION
**Pull request by mjoyce91**
Resolves TM-304 by updating styles and content on the Profile Dashboard page.

### CODE REVIEW

**Comment by mjoyce91** [comment]
Thanks, I'll update today

**Comment by mjoyce91** [comment]
Hey @rtirserio I'm looking at [this design](https://bahdigital.invisionapp.com/d/main#/console/13144552/296004016/preview) and I'm not sure what you mean by "per card". I did notice that "View More" should be "View more" based on the JIRA ticket, so I'm about to push an update for that.

**Comment by rtirserio** [comment]
@mjoyce91 - I mean the JIRA issue. Sorry for the confusion

**Comment by mjoyce91** [comment]
Ohh got it :smile:

**Pull request merged**
