### PR TITLE
[TM-5701-5702] Assignment Separations UI (Create/Edit)

### PR DESCRIPTION
**Pull request by jlam-mpc**
Updates:
- Converted AssignmentModal to a reusable ReactModal component
  - To create a modal, wrap the modal children with this component and add in the open boolean prop
- Split off Assignment tab into it's own component
- Fixed TMDatePicker text size styling and universal form styles
- Do not display a div for subheading if none exists for PositionExpandableContent (fixes odd spacing/styling)
- Renamed Assignments feature to AssignmentsSeparations (Assignments and Separations)

New:
- Created Separations tab on list page to view existing separations
- Created Separation component to be used in separations tab cards and combined modal

[TM-5701](https://metaphase.atlassian.net/browse/TM-5701)
[TM-5702](https://metaphase.atlassian.net/browse/TM-5702)

[TM-5701]: https://metaphase.atlassian.net/browse/TM-5701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TM-5702]: https://metaphase.atlassian.net/browse/TM-5702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by scott062** [comment]
image
New link route - heads up

**Comment by scott062** [comment]
image
Remove SSN

**Comment by scott062** [comment]
image
Optional: Add cal icon

**Comment by scott062** [comment]
image
Optional: Make text styling consistent for default "Select ..."

**Comment by scott062** [comment]
image
Optional: Should we move the check marks to be last in the list? Maybe a designer question about priority of information

**Comment by scott062** [comment]
@jlam-mpc Only two requested fixes, the others are optional for follow up ticket. I don't want them getting confused about the SSN which we are not implementing/showing in TMAP. And update link to maintain assignments

**Review by scott062 — CHANGES_REQUESTED** [review]
See above

**Comment by jlam-mpc** [comment]
> image New link route - heads up

Good catch- that's my bad

**Review by scott062 — APPROVED** [review]
Thanks Jeanie - great job refactoring and building out the new modal patterns for asgs/seps
💪 🧙‍♀️ 🎊

**Pull request merged**
