### PR TITLE
bid tracker hs register checkmark TM-3072

### PR DESCRIPTION
**Pull request by SidelineCory24**
To-Do

- [x] Show number instead of green checkmark on timeline when HS W/ Another Bidder Overlay displays
- [x] HS Registered Animation should only display when the Bidder has a HS on the position
- [x] Styling for other numbers on the timeline should not be impacted unless stated above

Screenshots are below to see what the styling should show for each point on the timeline.

**Note: Should work for condensed view as well**

### CODE REVIEW

**Comment by SidelineCory24** [comment]
**CDO View**
image

**Bidder View**
image

**Comment by SidelineCory24** [comment]
https://user-images.githubusercontent.com/55964163/181830395-d9aa8b82-da60-4d27-988b-50e885958ac7.mp4

**Comment by elizabeth-jimenez** [comment]
> **CDO View** image
> 
> **Bidder View** image
> 
> **CDO Condensed View** image
> 
> **Bidder Condensed View** image

great SS!

**Comment by pveland621** [comment]
Nice!

**Review by pveland621 — APPROVED** [review]

**Pull request merged**
