### PR TITLE
Fix/cycle position updates

### PR DESCRIPTION
**Pull request by rtirserio**
TM-939

Requires the API changes in https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/83

Some issues with the compare are still in progress but this should cover searching, favorites and export

### CODE REVIEW

**Comment by mjoyce91** [comment]
Are these fixes specifically for the 1.1 release? If so, I've created a tag, 1.1.1, that is a branch off of sprint-8 and includes Export fixes. The current staging branch is too far ahead of what is currently in 1.1.

https://github.com/MetaPhase-Consulting/State-TalentMAP/tree/1.1.1

**Comment by rtirserio** [comment]
@mjoyce91 yes this is specific to 1.1 is there a branch that i can target for this? it started off the staging branch

**Comment by rtirserio** [comment]
@mjoyce91 updated the branch target to release/1.1 let me know if thats the correct target

**Comment by mjoyce91** [comment]
@rtirserio - created a new branch that matches the release I created: `/release/1.1.1`

**Comment by mjoyce91** [comment]
The issue I see is that if we want to use the 1.1.1 branch, you'll need to branch off of that and cherry pick the commits that relate to your change, otherwise we're still pulling in the latest version of staging.

**Comment by rtirserio** [comment]
@mjoyce91 @burgwyn im creating a new PR into the release/1.1.1 branch with the commits cherry-picked. once i have that ready ill close this

**Comment by rtirserio** [comment]
closing. see #211

**Pull request closed without merging**
