### PR TITLE
storing sort in saved search TM-2372

### PR DESCRIPTION
**Pull request by SidelineCory24**
How to test:
Load save search for each
Test for AP and PV
- [x] add filters and save search without changing the sort by
- [x] add filters and a change the sort by, then save the search
- [x] add tandem filters and save search without changing the sort by
- [x] add tandem filters and a change the sort by, then save the search

### CODE REVIEW

**Comment by mjoyce91** [comment]
Should we exclude `ordering` from this function?

```js
export const ENDPOINT_PARAMS_TANDEM = {
  ...Object.assign({}, ...Object.keys(ENDPOINT_PARAMS).map(m => ({ [m]: `${ENDPOINT_PARAMS[m]}-tandem` }))),
  projectedVacancy: ENDPOINT_PARAMS.projectedVacancy,
  tandem: ENDPOINT_PARAMS.tandem,
};
```

**Comment by SidelineCory24** [comment]
> Should we exclude `ordering` from the map in this function?
> 
> ```js
> export const ENDPOINT_PARAMS_TANDEM = {
>   ...Object.assign({}, ...Object.keys(ENDPOINT_PARAMS).map(m => ({ [m]: `${ENDPOINT_PARAMS[m]}-tandem` }))),
>   projectedVacancy: ENDPOINT_PARAMS.projectedVacancy,
>   tandem: ENDPOINT_PARAMS.tandem,
> };
> ```
`ENDPOINT_PARAMS_TANDEM`/`VALID_TANDEM_PARAMS` is only being used as check inside of `cleanTandemQueryParams` in `utilities.js` which takes in parsedQuery which has `ordering` in it

**Comment by mjoyce91** [comment]
> > Should we exclude `ordering` from the map in this function?
> > ```js
> > export const ENDPOINT_PARAMS_TANDEM = {
> >   ...Object.assign({}, ...Object.keys(ENDPOINT_PARAMS).map(m => ({ [m]: `${ENDPOINT_PARAMS[m]}-tandem` }))),
> >   projectedVacancy: ENDPOINT_PARAMS.projectedVacancy,
> >   tandem: ENDPOINT_PARAMS.tandem,
> > };
> > ```
> 
> `ENDPOINT_PARAMS_TANDEM`/`VALID_TANDEM_PARAMS` is only being used as check inside of `cleanTandemQueryParams` in `utilities.js` which takes in parsedQuery which has `ordering` in it

Right, but would there be a need to have an `ordering-tandem` created by `${ENDPOINT_PARAMS[m]}-tandem`?

**Comment by SidelineCory24** [comment]
> > > Should we exclude `ordering` from the map in this function?
> > > ```js
> > > export const ENDPOINT_PARAMS_TANDEM = {
> > >   ...Object.assign({}, ...Object.keys(ENDPOINT_PARAMS).map(m => ({ [m]: `${ENDPOINT_PARAMS[m]}-tandem` }))),
> > >   projectedVacancy: ENDPOINT_PARAMS.projectedVacancy,
> > >   tandem: ENDPOINT_PARAMS.tandem,
> > > };
> > > ```
> > 
> > 
> > `ENDPOINT_PARAMS_TANDEM`/`VALID_TANDEM_PARAMS` is only being used as check inside of `cleanTandemQueryParams` in `utilities.js` which takes in parsedQuery which has `ordering` in it
> 
> Right, but would there be a need to have an `ordering-tandem` created by `${ENDPOINT_PARAMS[m]}-tandem`?

Ah okay that makes sense. Would handling it like `projected vacancy` make sense or delete it all together?
`ordering: ENDPOINT_PARAMS.ordering`

**Comment by mjoyce91** [comment]
@SidelineCory24 I think it's actually fine now that I'm looking at it again. We're already mapping some endpoint params to `-tandem` that don't need to be, like `postIndicators`.

**Pull request merged**
