### PR TITLE
TM-5556 Refine Remark Inserts

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
[TM-5556](https://metaphase.atlassian.net/browse/TM-5556)

[TM-5556]: https://metaphase.atlassian.net/browse/TM-5556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pveland621** [comment]
if you put in some text, plus sign is enabled but then if you delete whatever text is there, the plus sign is still enabled, allowing user to add remark with empty insertion:

image
image
image

image

**Comment by elizabeth-jimenez** [comment]
@pveland621 Done 🎊

**Comment by pveland621** [comment]
2 last minor questions:
1. confirmed that you can only add one of each remark? 
2. do we want to handle the edge case of a user entering a space as a remark insertion? currently a space is an acceptable insertion

**Comment by elizabeth-jimenez** [comment]
> 2 last minor questions:
> 
> 1. confirmed that you can only add one of each remark?
> 2. do we want to handle the edge case of a user entering a space as a remark insertion? currently a space is an acceptable insertion

1. Yea, can only add one of each remark
2. Yes, good catch! Done

**Review by M00staff — APPROVED** [review]
doing the honors for @pveland621 

🙌

**Pull request merged**
