### PR TITLE
Removed unused code

### PR DESCRIPTION
**Pull request by dihora-mayur**
- Removed unused code

### CODE REVIEW

**Comment by SidelineCory24** [comment]
need to remove `bidderPortfolioCountsFetchData` from here `src/actions/bidderPortfolio.test.js` as well

**Comment by dihora-mayur** [comment]
No wonder the test keeps failing. Thanks Cory!

From: SidelineCory24 ***@***.***>
Date: Friday, October 14, 2022 at 12:29 PM
To: MetaPhase-Consulting/State-TalentMAP ***@***.***>
Cc: Dihora, Mayur [USA] ***@***.***>, Author ***@***.***>
Subject: [External] Re: [MetaPhase-Consulting/State-TalentMAP] Removed unused code (PR #2364)

need to remove bidderPortfolioCountsFetchData from here src/actions/bidderPortfolio.test.js as well

**Comment by SidelineCory24** [comment]
> need to remove `bidderPortfolioCountsFetchData` from here `src/actions/bidderPortfolio.test.js` as well

once this change is done the test should start passing

**Review by SidelineCory24 — APPROVED** [review]
Looks good to go!🚀

**Pull request merged**
