### PR TITLE
Panel-Text-Language-TOD

### PR DESCRIPTION
**Pull request by cagbakwu**
https://metaphase.atlassian.net/browse/TM-4991

-When there is no Language data, display as None Listed instead of blank (all legs)
-When there is an IND (indefinite) TOD, the TED should display as N/A

Screenshot 2023-10-19 at 4 52 57 PM

### CODE REVIEW

**Review by M00staff — CHANGES_REQUESTED** [review]
This doesn't work. 

I also think this logic should probably be handled in the API layer. 

image

**Comment by cagbakwu** [comment]
> This doesn't work.
> 
> I also think this logic should probably be handled in the API layer.
> 
> image

@M00staff  Are you sure you pulled mine down? I am looking at it now and everything is working like its supposed to. Im looking at multiple cards.

Screenshot 2023-10-23 at 1 46 17 PM

Screenshot 2023-10-23 at 1 46 28 PM

**Comment by jlam-mpc** [comment]
> This doesn't work.
> 
> I also think this logic should probably be handled in the API layer.
> 
> image

I agree with Moose I looked at agenda.py in service folder and we could just replace the `-` return value with `None listed` and set ted to `N/A` if those conditions are met on the service layer too. This PR could be removed (not just for the heck of it but I think it's a little back and forth to return one pattern of denoting null values from the service and then converting it out on the frontend when we can just tackle it in one place.

**Comment by cagbakwu** [comment]
Closing and moving to BE

**Pull request closed without merging**
