### PR TITLE
bid tracker overlay collapse resolution bug

### PR DESCRIPTION
**Pull request by SidelineCory24**
I thought this was fixed but I guess not 🥴. Tested successfully for resolution and zoom.
image

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
@SidelineCory24 did you want help with this? Or just pushed to be safe?

**Comment by SidelineCory24** [comment]
> @SidelineCory24 did you want help with this? Or just pushed to be safe?

@elizabeth-jimenez oh no it's fixed/ready for review. I was posting the screenshot to show the bug.

**Comment by elizabeth-jimenez** [comment]
> > @SidelineCory24 did you want help with this? Or just pushed to be safe?
> 
> @elizabeth-jimenez oh no it's fixed/ready for review. I was posting the screenshot to show the bug.
> Is it still not working?

ooohh no, i was just confused lol! rip

**Review by mjoyce91 — APPROVED** [review]

**Comment by SidelineCory24** [comment]
> > > @SidelineCory24 did you want help with this? Or just pushed to be safe?
> > 
> > 
> > @elizabeth-jimenez oh no it's fixed/ready for review. I was posting the screenshot to show the bug.
> > Is it still not working?
> 
> ooohh no, i was just confused lol! rip

All good. It was deja vu with me and this ticket so I wasn't sure 😂

**Pull request merged**
