### PR TITLE
HS ribbon added to compare table

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
HS flag added to compare table.

- [x] 1920×1080
- [x] 1366×768
- [x] 1440×900
- [x] 1536×864
- [x] 2560×1440
- [x] 1280×720
- [x] 1024*768

### CODE REVIEW

**Comment by mjoyce91** [comment]
Screen Shot 2020-08-10 at 12 50 14 PM

Not a huge deal, but I'd see if you can get this to be a little more responsive at smaller resolutions

**Comment by elizabeth-jimenez** [comment]
> Screen Shot 2020-08-10 at 12 50 14 PM
> 
> Not a huge deal, but I'd see if you can get this to be a little more responsive at smaller resolutions

Wooow 🤮 . Def will address that :)

**Comment by mjoyce91** [comment]
@elizabeth-jimenez could be as simple as just showing the icon instead of the full ribbon at a certain resolution. If you go that route, check out the MediaQuery component

**Comment by elizabeth-jimenez** [comment]
> @elizabeth-jimenez could be as simple as just showing the icon instead of the full ribbon at a certain resolution. If you go that route, check out the MediaQuery component

I like that idea; ok, will do!

**Comment by elizabeth-jimenez** [comment]
image
😻

**Pull request merged**
