### PR TITLE
Position Manager filters TM-1860

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
Just dummy filters with dummy data; may want to update to use real data? "real" as in, import all the grades or skills, etc

~[Pause Merge](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1006)~

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
WIP tag added, going to update dropdowns to be `Picky`

**Comment by mjoyce91** [comment]
This looks really good! I know you're looking into moving to `picky`, but one thing I noticed was the vertical spacing for the dropdown labels (i.e., bring them down a little so that they're centered with the dropdown)

Screen Shot 2020-07-21 at 1 31 00 PM

**Comment by mjoyce91** [comment]
Shadow probably shouldn't "shine" up into the header like this:

Screen Shot 2020-07-21 at 1 34 24 PM

**Comment by elizabeth-jimenez** [comment]
> This looks really good! I know you're looking into moving to `picky`, but one thing I noticed was the vertical spacing for the dropdown labels (i.e., bring them down a little so that they're centered with the dropdown)
> 
> Screen Shot 2020-07-21 at 1 31 00 PM

Thanks! When i convert to picky i'll likely have to update most of the styles 😭   I'll be sure to make sure the labels are centered 😄 🔎 🕵️‍♂️

**Comment by elizabeth-jimenez** [comment]
> Shadow probably shouldn't "shine" up into the header like this:
> 
> Screen Shot 2020-07-21 at 1 34 24 PM

🕵️‍♂️  ooo good catch! I couldn't see it cause it kinda blended into the gold banner.

**Pull request merged**
