### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by mjoyce91**
A few accessibility fixes:
- Color contrast for the "back to top" button
- Use of negative tab-index on the `CSVLink` element (downloading exports), as this element doesn't actually perform the download, it's just a placeholder for the CSV. Previously, it was possible to tab to this element, click on it, and download an empty CSV file.

### CODE REVIEW

**Comment by burgwyn** [comment]
Apr-29-2019 13-00-25
Do you see the small bit of focus next to the button?

**Comment by mjoyce91** [comment]
Yeah, this PR should fix that. You're sure you pulled down this branch and refreshed?

**Comment by burgwyn** [comment]
Two things WAVE shows me:
1 - empty link on the export button - maybe add a hidden `<span>`?
2 - color contract on the "Save this search" text

**Comment by mjoyce91** [comment]
@burgwyn - the empty link should be irrelevant because we now hide that element. The error occurs on the generated <a> tag, not the actual <button>. The CSV library uses this <a> to generate the CSV, but it's not what the user actually interacts with.

**Pull request merged**
