### PR TITLE
TM-4446, remove completed status from panel meetings

### PR DESCRIPTION
**Pull request by M00staff**
A few notes:
- there is no mapping for the `COMP` value in the API - the values for `mdt_code` (which is the status) come directly from the FSBID side
- there was no need to update the filters, as the reference table already doesn't return a completed status 

image

[Ticket](https://metaphase.atlassian.net/browse/TM-4446)

image

image

### CODE REVIEW

**Review by jlam-mpc — APPROVED** [review]
Straightforward enough for me to approve BUT I wanted to ask if you've clarified whether the meaning of "Closed" in the filter is equivalent to "Complete".

**Comment by M00staff** [comment]
> Straightforward enough for me to approve BUT I wanted to ask if you've clarified whether the meaning of "Closed" in the filter is equivalent to "Complete".

good catch - double checked and it looks like (at least in dev) they are not one in the same
image

**Review by elizabeth-jimenez — APPROVED** [review]

**Comment by elizabeth-jimenez** [comment]
I didn't actually review, just wondering why the Approve label isnt getting added

**Review by elizabeth-jimenez — APPROVED** [review]
checking approve label workflow - ayyy it worked!

**Pull request merged**
