### PR TITLE
Fix the Go Back button, remove deprecated props

### PR DESCRIPTION
**Pull request by mjoyce91**
Resolves TM-1537

The main problem was that when you went BACK to a route, the Back Button on that screen would not display when it should have.

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
There is a little bit of an inconsistency. Sometimes when clicking View position, the back button just says 'Go Back' other times it says 'Go Back To Search' (or something like that). I'm trying to find why it sometimes gives one or the other.

**Comment by elizabeth-jimenez** [comment]
@mjoyce91 After lots of clicking, I couldn't find a helpful pattern. But when going to search and adding filters, or none, and then clicking View Position, three different button texts appear: 'Go back', 'Back To Search Results', and 'Back to Position Details' (yes, even though page is currently at position details). The button's functionality, however, remains the same and the search filters are saved.

**Comment by elizabeth-jimenez** [comment]
To replicate above issue:

Jenny -> Search -> View Position: Back to Search Results

Jenny -> Search -> View Position -> Add Summer 2019 Bid Cycle Filter -> View position -> Back to Search Results -> View Position: Go back

I think when no new filters are added, we get the Go back button

**Comment by mjoyce91** [comment]
Thanks @elizabeth-jimenez - yes, I'll need to add some wildcard matching... Right now I display "back to search results" if `route === '/details'`, but that obviously fails for `route === '/details?filter=1'`.

I think that's important enough that I'll try to fix it in this PR, so good catch 👍

**Comment by elizabeth-jimenez** [comment]
> Thanks @elizabeth-jimenez - yes, I'll need to add some wildcard matching... Right now I display "back to search results" if `route === '/details'`, but that obviously fails for `route === '/details?filter=1'`.
> 
> I think that's important enough that I'll try to fix it in this PR, so good catch 👍

Ah, that makes sense! If you like using regular expressions, this is nice tool: https://regexr.com/

Thanks! Glad to contribute 👍

**Comment by mjoyce91** [comment]
@elizabeth-jimenez - updated to use wildcard for /results*

**Pull request merged**
