### PR TITLE
Integrate data sync editor form with API

### PR DESCRIPTION
**Pull request by mjoyce91**
Updates existing data sync editor form to work with new PATCH data sync API endpoint.

Left some comments around how the PATCH endpoint calculates the `next_synchronization` property automatically based on `last_synchronization` + `delta`, and that because we might want to change that in the future, I've left in some commented components and functionality that would support the ability to edit the `next_synchronization` field should the API support it in the future.

### CODE REVIEW

**Comment by rtirserio** [comment]
@mjoyce91 i was unable to edit the sync job. Seeing INVALID DATE in the Time field. I could not change that field.

Screen Shot 2019-07-24 at 8 45 48 AM

Screen Shot 2019-07-24 at 8 46 36 AM

**Comment by mjoyce91** [comment]
Interesting, I'll take a look

**Comment by mjoyce91** [comment]
@rtirserio - if you update your config.json to use `"baseURL": "https://dev.talentmap.api.metaphasedev.com/api/v1"`, do you get the same issue? That would help me narrow it down to a data vs. browser issue.

**Comment by rtirserio** [comment]
@mjoyce91 changed the API and it worked so it looks like its my data that is causing the issue

**Pull request merged**
