### PR TITLE
Align bid count with data points in ResultsCondensedCard

### PR DESCRIPTION
**Pull request by mjoyce91**
Completes TM-337.

### CODE REVIEW

**Comment by rtirserio** [comment]
@mjoyce91 the cards on the search results are still pushed to the right. Does it make sense to make those consistent?

**Comment by mjoyce91** [comment]
@rtirserio good point. @cydneycappello , do we also want to move the Bid Count on the search results cards?

How the condensed cards look with this PR's update:
screen shot 2018-12-21 at 9 37 06 am

The current search results cards:
screen shot 2018-12-21 at 9 37 14 am

**Comment by cydneycappello** [comment]
search results - no add to bid list
You guys are right, I had to mock it up to see it. But I think it looks better in-line.

**Comment by mjoyce91** [comment]
Thanks, I'll update

**Comment by mjoyce91** [comment]
@rtirserio - just updated

**Pull request merged**
