### PR TITLE
integrate ai reference data

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**
## Current Status: Ready for review

### CODE REVIEW

**Comment by scott062** [comment]
Note to add common loading spinner to group ref data loading

**Comment by scott062** [comment]
Formatting and ordering of panel dates ref data - 
- Sort by category AND date? Or just by date? Cleaner way to sort/show them?
- Product Owner question - can you set a date to the past? If not, we can change the ref data filter call.

**Comment by elizabeth-jimenez** [comment]
image

**Comment by elizabeth-jimenez** [comment]
image

**Review by scott062 — APPROVED** [review]
Noice! I noticed some design things in addition to what I already commented. Position of the left/right spinners + Name Loading unrelated to Spinner (don't know if we want to change later). Looks good!

**Comment by elizabeth-jimenez** [comment]
> Noice! I noticed some design things in addition to what I already commented. Position of the left/right spinners + Name Loading unrelated to Spinner (don't know if we want to change later). Looks good!

I think we'll def want to incorporate the name into the spinner later

**Pull request merged**
