### PR TITLE
Use get to default to array

### PR DESCRIPTION
**Pull request by mjoyce91**
In DOS environment, if this data doesn't come through (such as a superuser who doesn't have any bureaus), then an uncaught error occurs. This defaults the output to an array to avoid that issue.

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
I think this may be handled in the updates in [PR 1627](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1627)?

**Comment by mjoyce91** [comment]
> I think this may be handled in the updates in [PR 1627](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1627)?

@elizabeth-jimenez not necessarily because the `find` could return null/undefined, which would result in an uncaught exception when trying to target `.data`

**Comment by elizabeth-jimenez** [comment]
> > I think this may be handled in the updates in [PR 1627](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1627)?
> 
> @elizabeth-jimenez not necessarily because the `find` could return null/undefined, which would result in an uncaught exception when trying to target `.data`

sooo trueee! nice find!

**Review by elizabeth-jimenez — APPROVED** [review]
🥮 👍

**Pull request merged**
