### PR TITLE
feature: enable location filter on PV. TM-949

### PR DESCRIPTION
**Pull request by rtirserio**
adds the location filter to the PV search

### CODE REVIEW

**Comment by mjoyce91** [comment]
When I add a post filter, I get a 500 error from http://localhost:8000/api/v1/fsbid/projected_vacancies/?limit=5&ordering=ted&page=1&position__post__in=281&projectedVacancy=projected&q= (using https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/108)

If it's just a matter of there being no results, could you send back our standard response with an empty results array?

**Comment by rtirserio** [comment]
@mjoyce91 you'll need to use the branch for the PR in the API project. Also, you need to update the mock-fsbid repo locally and run a docker-compose build on the API

**Comment by mjoyce91** [comment]
Okay thought I did both of those (using the API branch and rebuilding docker) but I'll try again

**Comment by mjoyce91** [comment]
@rtirserio still getting the same error. Is there a commit to mock-fsbid that needs to be pushed?

**Comment by rtirserio** [comment]
@mjoyce91 yes, and i just pushed it. sorry about that

**Comment by mjoyce91** [comment]
Same issue - here's an example request generated by the front-end:

http://localhost:8000/api/v1/fsbid/projected_vacancies/?limit=5&ordering=ted&page=1&position__post__in=287&projectedVacancy=projected&q=

Is `position__post__in` definitely the parameter that you want to use?

**Comment by rtirserio** [comment]
@mjoyce91 what is the error? I'm able to use `position__post__in` without issue. That is the correct name for the parameter

**Comment by rtirserio** [comment]
@mjoyce91 -- my bad. i got it fixed.

**Pull request merged**
