### PR TITLE
Update/consolidate ai styles

### PR DESCRIPTION
**Pull request by elizabeth-jimenez**

### CODE REVIEW

**Comment by elizabeth-jimenez** [comment]
agenda_item_maintenance: true
Panel Meetings Agenda Items
image

AIH - Row
image

AIH - Card
image

**Comment by elizabeth-jimenez** [comment]
agenda_item_maintenance: false (icon not clickable ✅)
Panel Meetings Agenda Items
image

AIH - Row
image

AIH - Card
image

**Comment by elizabeth-jimenez** [comment]
The previous SSs showed variance in stylings when flag flipped - which should not be the case. That has now been fixed

Agenda_Item_Maintenance = true (icon links to AIM ✅)

Panel Meetings AIs
Pasted Graphic 4

AIH - Row
Pasted Graphic 6

AIH - Card
Pasted Graphic 7

——————————————————————————————————————————————————————————————————————————————————————————
Agenda_Item_Maintenance = false (icon does not link to AIM ✅)

Panel Meetings AIs
Pasted Graphic 9

AIH - Row
Pasted Graphic 10

AIH - Card
Pasted Graphic 11

**Review by M00staff — APPROVED** [review]
it looks good - thanks for cleaning this up!

only one thing (that's not worth changing) ... when the feature flag is off, and the paper icon can't be clicked - why let the mouse cursor still change to a pointer?

**Comment by elizabeth-jimenez** [comment]
> it looks good - thanks for cleaning this up!
> 
> only one thing (that's not worth changing) ... when the feature flag is off, and the paper icon can't be clicked - why let the mouse cursor still change to a pointer?

That's currently all icons on TM 😅

**Pull request merged**
